# Lists

In [ ]:
#Q1
numbers= list(range(1,11))
new_list=[]
for i in range(len(numbers)):
    if i%2!=0:
        new_list.append(numbers[i])

print(new_list)

[2, 4, 6, 8, 10]


In [ ]:
#Q2

def common_elements(list1,list2):
    common_list=[]
    for i in list1:
        if i in list2:
            common_list.append(i)
    return common_list

list1=[1,2,3,4,5]
list2=[3,4,5,6,7]
print(common_elements(list1,list2))

[3, 4, 5]


In [ ]:
#Q3
def reversed_list(lst):
    reversed_list=[]
    for item in lst:
        reversed_list.insert(0,item)
    return reversed_list
print(reversed_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


In [ ]:
#Q4
def sum_of_elemnts(lst):
    sum=0
    for item in lst:
        sum+=item
    return sum
print(sum_of_elemnts([1,2,3,4,5]))


15


In [ ]:
#Q5
def second_largest(lst):
    lst.sort()
    return lst[-2]
print(second_largest([1,2,3,4,5]))

4


# Tuple

In [ ]:
#Q1
tuple1=(5,2,3,4,1)
max=tuple1[0]
min=tuple1[0]
for item in tuple1:
    if item>max:
        max=item
    if item<min:
        min=item
print(max)
print(min)

5
1


In [ ]:
#Q2

def swap_first_last(tuple1):
    # Convert the tuple to a list to allow modification
    list1 = list(tuple1)
    # Perform the swap using the list
    list1[0], list1[-1] = list1[-1], list1[0]
    # Convert the list back to a tuple
    tuple1 = tuple(list1)

    return tuple1
print(swap_first_last((1,2,3,4,5)))

(5, 2, 3, 4, 1)


In [ ]:
#Q3

tuple1=(5,2,3,4,1)
list1=list(tuple1)
list1.sort()
tuple1=tuple(list1)
print(tuple1)

(1, 2, 3, 4, 5)


In [ ]:
#Q4

tuple_count=(1,2,1,2,1,1,3,6,7)
list_count=list(tuple_count)
print(list_count.count(1))


#if i should not convert it to list,then i used the counter
count=0
for item in tuple_count:
    if item==1:
        count+=1
print(count)

4
4


# Dictionary

In [ ]:
#Q1

students={
    "Samar":99,
    "Mohammad":100,
    "Ammar":50,
    "Lama":33,
    "Wael":23
}
passed_students=[]
for key,value in students.items():
     if value>=50:
        passed_students.append(key)
print(passed_students)


['Samar', 'Mohammad', 'Ammar']


In [ ]:
#Q2
#merge two dictionaries into one
dict1 = {'a': 100, 'b': 200}
dict2 = {'x': 300, 'y': 200}
#the first way to update dict 3 two times
dict3.update(dict1)
dict3.update(dict2)

#the second way Using Dictionary Unpacking (**) and add them into dict3
#dict3 = {**dict1,**dict2}
print(dict3)

{'a': 100, 'b': 200, 'x': 300, 'y': 200}


In [ ]:
#Q3
dict1 = {'a': 100, 'b': 123456, 'c': 30930,'d':1003}
res=sorted(dict1,key=dict1.get,reverse=True)[0]
print(res)

b


In [ ]:
#Q4
def convert_dict(conv_dict):
      dict1={}
      for key,value in conv_dict.items():
          dict1[value]=key
      return dict1

print(convert_dict({'a': 100, 'b':300, 'y': 200}))

{100: 'a', 300: 'b', 200: 'y'}


In [ ]:
#Q5
def count_letters(s):
    letter_count={}
    for letter in s:
        if letter.isalpha():
            letter=letter.lower()
            if letter in letter_count:
                letter_count[letter]+=1
            else:
                letter_count[letter]=1
    return letter_count

print(count_letters("Hello World"))

{'h': 1, 'e': 1, 'l': 3, 'o': 2, 'w': 1, 'r': 1, 'd': 1}


# Set

In [ ]:
from typing import Union
#Q1
set1={1,2,3,4,5}
set2={4,5,6,7,8}
intersection=set1.intersection(set2)
union= set1.union(set2)

print(intersection)
print(union)

{4, 5}
{1, 2, 3, 4, 5, 6, 7, 8}


In [ ]:
#Q2

lst=[1,2,3,3,3,4,5,3,2,1,6,7,8,9]
set_=set(lst)
print(list(set_))


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
#Q3
def check_common_elements(set1,set2):
    if set1.intersection(set2):
        return True
    else:
        return False

print(check_common_elements({1,2,3,4,5},{4,5,6,7,8}))

True


In [ ]:
#Q4
#symmetric differene

set0={1,2,3,4,5}
set00={1,4,5,6,7,8}
print(set.symmetric_difference(set0,set00))

{2, 3, 6, 7, 8}


# If Condition

In [ ]:
#Q1
def check_num(num):
  if num>0:
    print(f"{num} is positive")
  elif num<0:
    print(f"{num} is negative")
  else:
    print(f"{num} is zero")

check_num(-1)
check_num(0)
check_num(1)

-1 is negative
0 is zero
1 is positive


In [ ]:
#Q2
#leap year
def check_leap_year(year):
   # divided by 100 means century year (ending with 00)
   # century year divided by 400 is leap year
   if (year % 400 == 0) and (year % 100 == 0):
        print("{0} is a leap year".format(year))

    # not divided by 100 means not a century year
    # year divided by 4 is a leap year
   elif (year % 4 ==0) and (year % 100 != 0):
       print("{0} is a leap year".format(year))

# if not divided by both 400 (century year) and 4 (not century year)
# year is not leap year
   else:
        print("{0} is not a leap year".format(year))

check_leap_year(2000)
check_leap_year(1900)
check_leap_year(2023)

2000 is a leap year
1900 is not a leap year
2023 is not a leap year


In [ ]:
#Q3
#checks if a character is a vowel or consonant
def check_vowel_consonant(char):
    if char.isalpha():
        if char.lower() in ['a','e','i','o','u']:
            print(f"{char} is a vowel")
        else:
            print(f"{char} is a consonant")

check_vowel_consonant('a')
check_vowel_consonant('b')
check_vowel_consonant('A')

a is a vowel
b is a consonant
A is a vowel


# While Loop

In [ ]:
#Q1
def print_numbers():
    i=1
    while i<=100:
      if i%17==0:
        break
      print(i)
      i+=1
print_numbers()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
#Q2

total=0
while True:
  num=int(input("Enter a number: "))
  if num==-1:
    break
  total+=num
print(f"The total is {total}")

Enter a number: 1
Enter a number: 6
Enter a number: 7
Enter a number: -1
The total is 14


In [ ]:
odd_num=1
print("The odd numbers are:")
while odd_num <= 50:
    if odd_num % 2 != 0:
        print(odd_num, end=' ')
    odd_num += 1

The odd numbers are:
1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 

# For Loop

In [1]:
#Q1
num=int(input("Enter a number: "))

def multiplication_table(num):
    for i in range(1,11):
        print(f"{num} x {i} = {num*i}")
multiplication_table(num)

Enter a number: 2
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20


In [4]:
#Q2
count=0
str=input("Enter a string: ")
for char in str:
    if char.lower() in ['a','e','i','o','u']:
      count+=1

print(f"The number of vowels in the string is {count}")

Enter a string: Hello world
The number of vowels in the string is 3


In [8]:
#Q3
lst=[1,2,3,4,5,6,2,3,4,9,11,22,13]
for item in lst:
  if item>5:
    print(item ,end=" ")

6 9 11 22 13 

# Function

In [9]:
#Q1
def factorial(n):
  res=1
  for i in range(1,n+1):
    res*=i
  return res
print(factorial(5))

120


In [10]:
#Q2
def is_palindrome(str_):
  if str_==str_[::-1]:
    return True
  else:
    return False
print(is_palindrome("madam"))



True


In [11]:
#Q3

def square_list(lst_):
  return [i**2 for i in lst_ ]

print(square_list([1,2,3,4,5]))

[1, 4, 9, 16, 25]


# Recursion

In [14]:
#Q1

def fibonacci_num(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fibonacci_num(n-1)+fibonacci_num(n-2)

print(fibonacci_num(10))

55


In [15]:
#Q2

def power(x,n):
  if n==0:
    return 1
  return x* power(x,n-1)

print(power(2,3))

8


In [16]:
#Q3

def rec_sum(lst):
  if not lst:
    return 0
  else:
    return lst[0]+rec_sum(lst[1:])

print(rec_sum([1,2,3,4,5]))

15


# Break and Continue

In [11]:
#Q1

for i in range(1,21):
     if i % 3 == 0:
       continue
     print(i,end=" ")



1 2 4 5 7 8 10 11 13 14 16 17 19 20 

In [14]:
#Q2

for i in range(1, 51):
    if i % 13 == 0 and i % 7 == 0:
        break
    print(i,end=" ")


1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 

In [21]:
#Q3

lst = [1, 3, 5, 7, 8, 9, 10, 11, 12]
for num in lst:
    if num % 2 == 0:
        break
    print(num ,end=" ")

1 3 5 7 

# Lambda

In [26]:
#Q1
tuples=[(1,4),(4,3),(1,6),(7,8),(7,1)]
tuples.sort(key=lambda x:x[1])
print(tuples)

[(7, 1), (4, 3), (1, 4), (1, 6), (7, 8)]


In [28]:
#Q2
squares=lambda x:x**2
print(squares(5))

25


In [29]:
#Q3
lst=[1,2,3,4,5,6,7,8,9,10]
odd_numbers=list(filter(lambda x:x%2!=0,lst))
print(odd_numbers)

[1, 3, 5, 7, 9]


# Classes and Object-Oriented Programming

In [30]:
#Q1

class car :
  def __init__(self,brand,model,year):
    self.brand=brand
    self.model=model
    self.year=year

  def display_info(self):
    print(f"This is a {self.year} {self.brand} {self.model}")

my_car=car("Toyota","Camry",2022)
my_car.display_info()


This is a 2022 Toyota Camry


In [35]:
#Q2
class num_of_objects:
  count = 0
  def __init__(self):
    num_of_objects.count+=1

  @classmethod
  def count_objects(cls):
    return cls.count

obj1=num_of_objects()
obj2=num_of_objects()
obj3=num_of_objects()
print(num_of_objects.count_objects())


3


In [41]:
#Q3
class parent:
  def __init__(self,name,age):
    self.name=name
    self.age=age
    print(f'Im the PARENT and my Name is {name} and my Age is {age}')

class child(parent):
  def view(self):
    print("Hello Im the CHILD")

obj=child("Ali",43)

obj.view()

Im the PARENT and my Name is Ali and my Age is 43
Hello Im the CHILD


In [42]:
#Q4
class Dog:
  def make_sound(self):
    print("Woof!")

class Cat(Dog):
  def make_sound(self):
    print("Meow!")

dog=Dog()
cat=Cat()

dog.make_sound()
cat.make_sound()

Woof!
Meow!


In [48]:
#Q5
from abc import ABC,abstractmethod

class Shape(ABC):
  @abstractmethod
  def area(self):
    pass

class Rectangle(Shape):
  def __init__(self,length,width):
    self.length=length
    self.width=width

  def area(self):
    rect_area=self.length*self.width
    print(f'Area of Rectangle is: {rect_area}')

class Circle(Shape):
  def __init__(self,radius):
    self.radius=radius

  def area(self):
    circle_area=3.14*self.radius**2
    print(f'Area of Circle is: {circle_area}')

rectangle=Rectangle(4,5)
circle=Circle(3)

rectangle.area()
circle.area()

Area of Rectangle is: 20
Area of Circle is: 28.26


In [53]:
#Q6

class get_set:
  def __init__(self):
    self._value=None

  def get_value(self):
    return self._value

  def set_value(self,value):
    self._value=value

obj=get_set()
obj.set_value(10)
print(obj.get_value())
obj.set_value(20)
print(obj.get_value())

10
20


# JSON

In [55]:
#Q1
import json

def dict_to_json(dict):
  return json.dumps(dict)

dict1 = {'a': 100, 'b': 200}
print(dict_to_json(dict1))

{"a": 100, "b": 200}


In [64]:
#Q2
import json

''' I asked chatgpt to generate some json data to be used here'''


def read_data_from_json(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
#Q2
import json



def read_data_from_json(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data
for data in read_data_from_json("/content/sample_data/anscombe.json")[:11]: #Read only thw first ten rows in json file
  print(data)


{'Series': 'I', 'X': 10.0, 'Y': 8.04}
{'Series': 'I', 'X': 8.0, 'Y': 6.95}
{'Series': 'I', 'X': 13.0, 'Y': 7.58}
{'Series': 'I', 'X': 9.0, 'Y': 8.81}
{'Series': 'I', 'X': 11.0, 'Y': 8.33}
{'Series': 'I', 'X': 14.0, 'Y': 9.96}
{'Series': 'I', 'X': 6.0, 'Y': 7.24}
{'Series': 'I', 'X': 4.0, 'Y': 4.26}
{'Series': 'I', 'X': 12.0, 'Y': 10.84}
{'Series': 'I', 'X': 7.0, 'Y': 4.81}
{'Series': 'I', 'X': 5.0, 'Y': 5.68}


In [67]:
#Q3
data={'name':'John','age':30,'city':'New York'}

with open('data.json','w') as file:
  json.dump(data,file,indent=4)


# NUMPy

In [73]:
#Q1
import numpy as np
array_of_zeros=np.zeros((3,3))
print(array_of_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [78]:
#Q2

import numpy as np
array=np.random.randint(1,101,10)
print(array)

[38  2 72 68 62 25 86 63 73 28]


In [81]:
#Q3

import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10])
print("Mean =",  np.mean(array))
print("Median =",  np.median(array))
print("STD =",  np.std(array))

Mean = 5.5
Median = 5.5
STD = 2.8722813232690143


In [85]:
#Q4
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9,10,34,56])
array=array.reshape(3,4)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 34 56]]


In [89]:
#Q5
import numpy as np

array1=np.array([1,2,3,4,5])
array2=np.array([6,7,8,9,10])
array3=array1+array2
print(array3)

[ 7  9 11 13 15]


In [90]:
#Q6
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)
print(result)


[[19 22]
 [43 50]]


In [94]:
#Q7
import numpy as np
arr = np.array([[1, 2],
              [3, 4],[5,6]])


# Find max and min values
max_val = np.max(arr)
min_val = np.min(arr)

# Find indices of max and min values
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)

print(f"Maximum value: {max_val} at index {max_idx}")
print(f"Minimum value: {min_val} at index {min_idx}")



Maximum value: 6 at index 5
Minimum value: 1 at index 0


In [96]:
#Q8

import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10,11,12],
    [13,14,15,16]
])

sliced_Arr = A[:3, :2]

print(sliced_Arr)


[[ 1  2]
 [ 5  6]
 [ 9 10]]
